
<textarea class="code">
{
  'name': 'Ty Overby',
  'phone': '(253) 514-9370'
  'email': 'ty@pre-alpha.com',
  'homepage': 'tyoverby.com',
  'resume': 'tyoverby.com/resume',
  'education': [
    {
      'institution': 'University of Washington',
      'study': 'Computer Science',
      'degree': 'Bachelors',
      'start_date': 'Mon Aug 27 2012',
      'end_date': undefined
    }
  ],
  'past_work': [
    {
      'company': 'Google',
      'title': 'Software Developer Intern',
      'start_date': 'Mon Jun 17 2013',
      'end_date': 'Fri Sep 15 2013'
    }
  ]
}
</textarea>
