
<!DOCTYPE html>
<html>
    <head>
        <title> Ty Overby </title>
        <link rel="stylesheet" href="./position.css">
        <link rel="stylesheet" href="./style.css">
    </head>

    <body>
        <section id="wrapper">
        <header> Ty Overby <br/> <span id="header-desc"> Sometimes I write computer programs </span> </header>
            <nav class="stretch">
                <ul>
                    <li> About Me </li>
                    <li> Resume </li>
                    <li> Projects </li>
                    <li> Gists </li>
                </ul>
            </nav>

            <article>
