<h2>Education</h2>

<p>I began learning programming early in middle school, however, my
education took off when Udacity and Coursera launched, offering free online
classes. I am currently a computer science major at the University of
Washington Seattle.</p>

<table>
    <tr>
        <td colspan="2">University of Washington</td>
    </tr>

    <tr>
        <td>CSE 311 Fundamentals of Computing.</td>

        <td>Fundamentals of logic, set theory, induction, and algebraic
        structures with applications to computing; finite state machines;
        and limits of computability.</td>
    </tr>

    <tr>
        <td>CSE 390 a Programming Tools</td>

        <td>Basics of Unix/Linux environment, version control, text
        processing, scripting, regular expressions.</td>
    </tr>

    <tr>
        <td>CSE 341 Programming Languages</td>

        <td>A look at the semantics and idioms of 3 programming languages:
        SML, Racket, and Ruby. Taught by Dan Grossman in conjunction with
        the online Coursera class of the same name.</td>
    </tr>

    <tr>
        <td>CSE 351 The Hardware/Software Interface</td>

        <td>Examines key computational abstraction levels below modern
        high-level languages; number representation, assembly language,
        introduction to C, memory management, the operating-system process
        model, high-level machine architecture including the memory
        hierarchy, and how high-level languages are implemented.</td>
    </tr>

    <tr>
        <td>CSE 332 Data Abstractions</td>

        <td>Covers abstract data types and structures including
        dictionaries, balanced trees, hash tables, priority queues, and
        graphs; sorting; asymptotic analysis; fundamental graph algorithms
        including graph search, shortest path, and minimum spanning trees;
        concurrency and synchronization; and parallelism.</td>
    </tr>

    <tr>
        <td colspan="2">Coursera/Udacity</td>
    </tr>

    <tr>
        <td>Artificial Intelligence</td>

        <td>Taught by Sebastian Thrun and Peter Norvig, the class
        introduces students to the basics of Artificial Intelligence, which
        includes machine learning, probabilistic reasoning, robotics, and
        natural language processing.</td>
    </tr>

    <tr>
        <td>Programming Languages</td>

        <td>An introduction to the fundamentals of programming languages.
        Key concepts include how to specify and process valid strings,
        sentences and program structures.</td>
    </tr>

    <tr>
        <td>Functional Programming in Scala</td>

        <td>A hands-on course that introduces the cornerstones of
        functional programming using the Scala programming language.
        Students will also develop a solid foundation for reasoning about
        functional programs, by touching upon proofs of invariants and the
        tracing of execution symbolically.</td>
    </tr>
</table>
