<style>
    .noborder,
    .noborder tr,
    .noborder td {
        border:none;
    }
</style>

<table class="noborder" style="width:100%;">
    <tr>
        <td>Name:</td>
        <td>Phone:</td>
        <td>Email:</td>
        <td>Website:</td>
        <td>Resume:</td>
    </tr>
    <tr>
        <td>Ty Overby</td>
        <td>(253)-514-9370</td>
        <td>ty@pre-alpha.com</td>
        <td>tyoverby.com</td>
        <td>tyoverby.com/resume</td>
    </tr>
</table>
