<h2>Projects</h2>

<p>
    All of these projects are done on my own time completely unrelated to
    any school work. The projects hosted on <a href=
    "https://github.com/TyOverby">my github page</a> date back 2 years; they
    are mostly unfinished, and some are in a state of disrepair. The ones
    listed below are the projects that I am most proud of.
</p>

<table style="border: 1px solid black">
    <thead>
        <tr>
            <td>Project</td>
            <td>Description</td>
            <td>Tech</td>
        </tr>
    </thead>

    <tr>
        <td>Write AI</td>
        <td>An online site + API that allows other programmers to write
        artificial intelligence to play against other artificial intelligence
        online.  The project is heavily inspired by the Google AI competition
        that I competed in.</td>

        <td>
            <ul>
                <li>Javascript</li>
                <li>Node.js</li>
                <li>Websockets</li>
        </td>
    </tr>

    <tr>
        <td>Lisp-&gt;Any</td>

        <td>An extensible compiler that takes a program made up of s-expressions
        and a file of transformation rules and produces an output file of those
        rules applied to the program.  It has been used successfully to write
        lisp-to-javascript, sExpressions-to-html, and sExpressions-to-LaTeX.</td>

        <td>
            <ul>
                <li>Scala</li>
                <li>Lisp</li>
                <li>Javascript</li>
            </ul>
        </td>
    </tr>

    <tr>
        <td>CanvaS</td>

        <td>A domain specific language for creating and manipulating images.
        Written and consumed in Scala.</td>

        <td>
            <ul>
                <li>Scala</li>
                <li>Image Processing</li>
            </ul>
        </td>
    </tr>

    <tr>
        <td>DCPUtilities</td>

        <td>An emulator for the DCPU, a 16 -bit CPU designed by Markus Persson.
        Written in Java and comes with a GUI and assembler.  It made me conscious of
        low-level optimizations.</td>

        <td>
            <ul>
                <li>Java</li>
                <li>Assembly</li>
                <li>Junit</li>
            </ul>
        </td>
    </tr>

    <tr>
        <td>Ants AI</td>

        <td>An game-playing artificial intelligence made to compete in the Google AI
        Challenge.</td>

        <td>
            <ul>
                <li>Java</li>
                <li>Networking</li>
            </ul>
        </td>
    </tr>
</table>
