<h2>Languages / Technologies</h2>

<p>While I tend to be more of a jack-of-all-trades, the following languages
and technologies are what I am most familiar with.</p>

<table>
    <thead>
        <tr>
            <td>Name</td>
            <td>Description</td>
            <td>Skill</td>
            <td>years</td>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>Scala</td>
            <td>Language of choice for any desktop and server programs.
            The combination of functional/oop concepts make abstractions easy
            for me to implement and use.</td>
            <td>High</td>
            <td>1</td>
        </tr>

        <tr>
            <td>Javascript</td>
            <td>Used on almost all my web-facing projects; I'm a proponent of
            moving as much logic to the client as possible.</td>
            <td>High</td>
            <td>3</td>
        </tr>

        <tr>
            <td>Java</td>
            <td>My first programming language, and the one that I have most
            experiance in.  Because of Scala, the only time I program in Java
            any more is for homework assignments.</td>
            <td>High</td>
            <td>5</td>
        </tr>

        <tr>
            <td>Python</td>
            <td>Mainly used for small programs or automation of tasks, Python
            is a great replacement for bash programs, though I rarely go much
            further with it.</td>
            <td>Good</td>
            <td>3</td>
        </tr>

        <tr>
            <td>Git</td>
            <td>Git is used for anything from my homework to my more serious
            projects.</td>
            <td>Good</td>
            <td>3</td>
        </tr>

        <tr>
            <td>Linux</td>
#undef linux
            <td>My development environment is focused around the GNU/linux
            toolchain. While I can operate in almost any *nix environment, I am
            fond of Debian and Debian's child distros.</td>
            <td>Good</td>
            <td>4</td>
        </tr>
    </tbody>
</table>
