<h2> Work Experience </h2>

<table>
    <thead>
        <tr>
            <td> Company </td>
            <td> Title </td>
            <td> Time Span </td>
            <td> Description </td>
            <td> Tech </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Google </td>
            <td> Engineering Intern </td>
            <td> June&nbsp;2013 to September&nbsp;2013 </td>
            <td>
Intern on the Google Chrome Mediastack team, the team that works on all
aspects of audio/video inside Chrome.  I extended their logging infrastructure on
the backend and made a web-based UI to visualize it.
            </td>
            <td>
                <ul>
                    <li>C++</li>
                    <li>Javascript</li>
                </ul>
        </tr>
    </tbody>
</table>



